GROCERY_STORES = [
  "Assaí",
  "Açougue",
  "Campeão",
  "Carrefour",
  "Casas Pedro",
  "Delicatessen Genérica",
  "Feira",
  "Guanabara",
  "Hortifruti",
  "Inter",
  "Jinlong",
  "Lojas Americanas",
  "Merca Dez",
  "Mundial",
  "Padaria",
  "Prezunic",
  "Princesa",
  "Pão de Açúcar",
  "Rede Economia",
  "SuperPrix",
  "Supermarket",
  "Ultra",
  "Zona Sul",
  "Outro",
]
